// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhyqNtoueG8IuU9aPLQSybMKvGdAl3krc',
    appId: '1:1068006410663:web:a626323667c1e5604dce82',
    messagingSenderId: '1068006410663',
    projectId: 'fairshare-e79b2',
    authDomain: 'fairshare-e79b2.firebaseapp.com',
    storageBucket: 'fairshare-e79b2.firebasestorage.app',
    measurementId: 'G-26H84PKK4C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-WabcO3gqMZDD_HgM14K0p8QH0nkTchw',
    appId: '1:1068006410663:android:8ab9c93666bb58404dce82',
    messagingSenderId: '1068006410663',
    projectId: 'fairshare-e79b2',
    storageBucket: 'fairshare-e79b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCie9NAyCCNKRAJLMHlMjivI-PE1rxaMwM',
    appId: '1:1068006410663:ios:5863e87673fe2b724dce82',
    messagingSenderId: '1068006410663',
    projectId: 'fairshare-e79b2',
    storageBucket: 'fairshare-e79b2.firebasestorage.app',
    androidClientId: '1068006410663-ti1ntk2d6ebudan6nh271k6hf13mnh73.apps.googleusercontent.com',
    iosClientId: '1068006410663-lqldh2r8t6vfifs7nnrdlkdfl8c9qqm2.apps.googleusercontent.com',
    iosBundleId: 'com.example.fairShare',
  );

}